let arr = [
    [ "(B) Their subconscious knew that Korvin was an insoluble problem. This same subconscious led them to provide resources for his escape so they wouldn't have to deal with him anymore.", "(A) It means that the Tr'en put Korvin under drug hypnosis while they taught him their language.", "(B) Korvin said truths that literally answered the Tr'en's questions but evaded the intent behind their questions. .", "(B) There weren't any other prisoners in the jail because virtually all of the Tr'en obey the Ruler. Those who don't obey are executed.", "(B) Because it's too mathematical and doesn't account for motivations, emotions, and what's left unsaid.", "(D) Yes, because the ruler says the he wants to know about Earth's weapons, plans, and fortifications.", "(D) The frown is physically horrible because the Tr'en have fifty-eight, pointed teeth.", "(A) He was adopted by the previous Ruler.", "(D) Because they misinterpreted his positive responses to his \"failure\" as anti-Earth.", "(B) Ensure the Tr'en evolve in their thinking before they start interstellar travel", "(A) He represented an unsolveable problem", "(D) Because the Tr'en do not infer the situational meaning of a question", "(C) human physiology, weapons, name, location, government", "(D) 406", "(C) Tr'en\n", "(C) The Ruler is adopted by the previous Ruler" ],
    [ "(C) He could not have gotten back home without being found out", "(C) The secret service budget was small", "(A) They suspected it but did not want to print this kind of story", "(D) Only the private quarters or the office restroom", "(D) Through the gate", "(D) It would be almost impossible for Clinton to have had an affair without the Secret Service knowing.", "(D) His aids, secretary, drivers, guards, Secret Service, the domestic staff, and many friends and family members of both parties.", "(D) After his death, the number of Secret Service agents multiplied exponentially, meaning that the President was virtually never alone.", "(A) He has to invite his trusted friends and staffers for a getaway, not invite his wife, and ensure that the lady friend is on the guest list.", "(D) To have a conjoining room with an aid, have the woman go to the aid's room, then come through the conjoining door. When the evening is over, she goes back the way she came.", "(A) about 15\n", "(B) The Washington Times is expressing great excitement about a new book written by a former FBI agent.\n", "(D) about 99" ],
    [ "(A) Even though they did not seem to be directly involved or cause problems because they did not quit their jobs on principle, they were at fault.", "(B) Yes, because they pretend to despise White House scandals such as this, yet, they could not get enough of it.", "(D) Chelsea", "(D) She stood by him even though she knew he was guilty of the affair.", "(B) He used his time as pastoral counsel for Clinton to gain media attention.", "(C) Individuals/groups were usually ranked from least liked to most liked.", "(B) It's consistently seen as a good thing.", "(C) Slate attempts to address the various ways in which the public views those involved in the scandal, and speculates upon whether those views are accurate.", "(A) Wrote two memoirs for profit as a result of the scandal.", "(B) Both of them were viewed with some sympathy, but Chelsea was deemed more deserving of sympathy because Hillary was somewhat complicit.", "(B) James Carville, Lanny Davis, Bob Barr, Erskine Bowles" ],
    [ "(B) He needs to maintain control over the relationship with the Hans", "(B) The same thing the Hans want with it", "(C) Hand-thrown implements", "(B) Pa was running to safety and was then killed to spare the rest of the people on the plain", "(C) Survival itself is difficult", "(C) No, he just wanted to point out injustice", "(A) No, he hated the systems enforced by his community.", "(D) A boy realizes the full extent to which his community oppresses him." ],
    [ "(C) He was reduced to particles", "(C) She painstakingly disciplined herself to keep wrinkles from forming", "(B) He was shocked that she had masterminded a way onto the flight", "(A) Unknown", "(D) Once traveling faster than light was possible, she thought she might continually do this to remain young", "(A) No, only Earth", "(D) We don’t know for sure from the story", "(A) Neither character knows about or cares for the other too much.", "(B) Not really. Ninon sees him as a pawn to hijack the flight, and if Robert truly loved Ninon he probably wouldn't end up participating in the space travel.", "(C) A woman has a plan to reverse her aging process and the reader sees her follow through with it.", "(B) Guns that freeze people in time to prevent them from aging", "(B) She wouldn't have been able to hijack the flight because Robert wouldn't want to date someone as old as her.", "(C) Ninon would've held him at gunpoint or drugged him until they had successfully completed takeoff.", "(C) It was to show how much thought Ninon has put into making her plan and how determined she is to see it succeed." ],
    [ "(D) O.K./OK", "(D) Because he realizes he's sharing news that he he hadn't meant to disclose so soon.", "(D) Because Skipper wants the new chef to cook marsh-duck and all the fixings.", "(B) effeminate behavior and taste is not incompatible with roughness and toughness", "(B) Because the Skipper considered himself smarter and more experienced than the new cook.", "(D) He realized by surrendering, the Alliance could use their ship to sneak into Federation territory unnoticed.", "(D) The Skipper's would have set course for Iris from the beginning.", "(A) He didn't" ],
    [ "(B) He felt he would collect a reward along the way", "(A) He learned Kal-Jmar didn’t contain secrets and treasures", "(A) Unknown", "(B) Syme was intrigued by Tate’s mission and joined on", "(A) Element of surprise", "(C) It’s not revealed how they detect them", "(B) Mind reading", "(C) Syme would've fallen to his death.", "(C) A criminal teams up with a scientist to explore a dangerous area." ],
    [ "(C) He has a sense of duty to not let innocent people die", "(A) A delivery ship discovers and saves two other ships", "(C) Their minds aren’t changed", "(B) They meet during the course of the story and become easy friends", "(D) It’s not known", "(A) Many things are going wrong", "(A) Zero", "(C) Hendricks’ father built the ship and trained her on it", "(D) Possibly, the Captain has feelings for her by the end but it remains unclear", "(C) It's an old ship and its predecessors previously failed in their missions", "(B) He uses lots of technical details and technologies to immerse the reader in the lore", "(A) The story remains relatively calm except for the climax", "(B) He's actively sexist with regard to his crew members", "(B) A sci-fi fan who likes suspense and watching friendships grow", "(D) For the most part, they succeeded on their mission but the Captain and Ivy aren't together" ],
    [ "(C) Humans are capable of treating anyone as kin", "(C) Bonding is more important to human capacity to love than genetic relationship", "(C) We fail to see that all modern humans share most of their genes in common, thus, helping any human is helping our genes pass on even if they are unrelated", "(A) Limiting love to those you are directly genetically related to is nonsensical from both ethical and genetic selection perspectives", "(B) Traits of kinship were important to familial genetics being passed on, thus kinship was also selected for in early human evolution", "(A) Full siblings", "(D) Traits for kinship are throughout the entire human population now, thus supporting only kin is less important in the modern world for kinship to persist", "(B) Just because a behavior is natural to animals does not mean it is considered ethical", "(D) The author posits that ethical treatment of all humans regardless of kin-status is most important", "(A) The daughter didn't spend time with you (nor did you with her) when she was little, so lots of bonding time was lost.", "(B) Oxytocin and Pitocin are functionally similar but, but one of the two would naturally be produced by a biological mother.", "(B) You're closely enough related to other non-familial humans that shared genes should not be the reasoning to give gifts to your kids over helping the homeless.", "(A) The overall tone is conversational, with the occasional funny moment or comedic example.", "(C) How geographic and cultural differences impact family-raising strategies and bonding styles.", "(C) If we help them succeed biologically, when they have kids they pass on DNA that matches some of our own.", "(B) A potential parent deciding between adopting a child and having a biological child.", "(D) An article in a popular newspaper's science section" ],
    [ "(C) 6", "(C) He didn't want to leave but was motivated by the pay", "(A) He doesn't want them to join Dixon", "(C) He shared that he wanted to be naked outdoors", "(D) Elated to finally be released", "(C) Colleagues, but they are not friends", "(C) They have artificial gravity in their living quarters", "(B) His technical skills and leadership" ],
    [ "(B) A person who illegally gains passage into space", "(A) She was expecting a baby", "(D) For her husband to fall back in love with her", "(D) Her dad had died in a rocket launch", "(B) She thought her husband loved the attendant", "(A) She resented that he wanted to leave her and go to space", "(A) Freefall", "(B) Close colleagues that are bound by duty", "(A) He is bound by duties that mean he is often away and she is usually unable to join him", "(A) Those with certain maladies are unable to travel in space without dying", "(B) An accomplice to Marcia’s plan" ],
    [ "(B) He felt like he might become unemployed because of the Actuarvac.", "(B) He is a very tall man.", "(D) No, because the people of Granite City are unusually prone to accidents/injury.", "(A) No, because Granite City was not making false insurance claims.", "(A) Yes, because the granite being shipped to other places out of Granite City is what is causing the problems for the people.", "(C) Madison is reluctant to believe Parnell.", "(A) His perception of Granite City would have been misconstrued because he would have lacked an explanation to why the people of Granite City are the way that they are.", "(A) In order to hopefully discover some red-flag indicators of insurance fraud.", "(A) He was too tall for most models and disliked the business decisions of American automakers.", "(D) It was very unsafe to drive any vehicles in Granite City.", "(A) It would begin to affect his memory later.", "(D) The haphazard way the granite was harvested and the bloody scene nearby reminded him of it.", "(A) Something about the granite creates an inability to predict when an accident may occur.", "(C) They are scared of losing their livelihood.", "(D) Their psionic deficiency rendered them incapable of essential human logic and reasoning.", "(D) He felt there was a criminal undercurrent to the situation.", "(A) about 4571 words\n", "(C) The speaker feels American cars have transitioned from passenger cars to cargo trucks\n", "(A) Parnell\n" ],
    [ "(D) An upscale and high-tech retreat.", "(D) Yes, because Harper also had a frustrating experience with the robots.", "(C) He would believe that robots do not excel in customer service, and they are better at less personable jobs.", "(D) Yes, because the human desk clerk had given him the wrong room.", "(A) Jake Ellis wanted to receive wellness treatments while Harper simply wanted an uninterrupted stay.", "(D) The hotel was failing, so the company was happy to get rid of the robots.", "(D) Sourcing water on Mars.", "(D) He realized he could profit from a scientific breakthrough.", "(B) He appreciated machine silence and accuracy.", "(D) He was starting to agree that human customer service might be preferable to robots.", "(B) They thought he was Jake Ellis.", "(C) He would be blamed for the mess Harper created during his outburst.", "(A) Operation Robot was a failed experiment and had lost too much money.", "(A) He traded out the factory workers for robots, and the factory workers took over the hotel jobs.", "(C) He gave him a large stock in Hagerty's Enzymes.", "(C) about 508\n", "(A) Clerk was about to deposit a card in the punch box before he was interrupted.\n", "(A) 12" ],
    [ "(B) Asa is afraid of Dorr, especially after being framed.", "(B) Asa would have become a muck man anyways because that was his original intention.", "(B) A frog-shaped body helped better cross the terrain on Jordan's Planet.", "(D) Completely inhospitable for human life without proper interventions.", "(D) Kershaw and Furston were essential in helping Asa assimilate to his job as a muck man.", "(A) She believes he is not competent to run the Hazeltyne company.", "(D) Asa would have been eaten by a Slider.", "(B) It is a very dangerous job that only prisoners would be desperate enough to do to lower their prison sentence.", "(D) He is seeking revenge.", "(A) Efficient labor and reduced prison sentences.", "(A) Studying Slider eggs in their natural habitat.", "(B) They are converted back to their normal body and returned to Earth.", "(A) Graybar's discoveries could ruin the Hazeltyne business.", "(B) To demonstrate the impossibility of escaping imprisonment and seeking refuge on Jordan's Planet.", "(B) The gravity on Jordan's Planet was different from that on Earth.", "(A) A frog.", "(D) about 5", "(A) about 38", "(B) A doctor from the Conversion Corps" ],
    [ "(B) She was upset about his visit to the chamber", "(D) Terra", "(D) He was the only one who had been to the outer planets before", "(C) He could relate Randall's behavior to his experience with Koerber", "(A) Drifting in space, possibly in very small pieces.", "(C) He missed a call-out to help capture a space pirate and was disciplined by his employer, plus he lost his girlfriend.", "(C) The Martian is jealous of Dennis because of the Mercurean dancer at the bar who is coming on to him.", "(A) Because the Martian was a space pirate, and the police were pleased at being able to grab him, and gave Dennis the credit.", "(A) She gave him a poisonous look.", "(D) He thought there was a pretty good chance Dennis would die during the mission.", "(A) It's just about the fastest ship out in space, a huge advantage.", "(B) They didn't have any spare time. They ran training exercises on procedures and weapons over and over to be ready.", "(C) With the jets still on, the magnetic repulsion plates could not be activated, resulting in them being tractored in by Koerber's ship.", "(A) about 4748\n", "(B) He dodged the Martian's rush and then struck him below the waist and to the chin.\n", "(A) Bertram \n" ],

]

let merged = [];

for (let i = 0; i < arr.length; i++) {
    for (let j = 0; j < arr[i].length; j++) {
        merged.push(arr[i][j]);
    }
}

// f1 score if all As

let total = merged.length;

let correct = 0;

for (let i = 0; i < merged.length; i++) {
    let tp = 0;
    let fp = 0;
    let fn = 0;
    if (merged[i].charAt(1) === "A") {
        tp = 1;
    }
    else {
        
    }
}

console.log("Total: " + total);
console.log("Correct: " + correct);
console.log("F1 Score: " + (correct / total).toFixed(2));